name: Laravel CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, bcmath, pdo, mysql, xml
      - uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
      - run: composer install --prefer-dist --no-progress --no-suggest
      - run: chmod -R 777 storage bootstrap/cache
      - run: |
          cp .env.example .env
          php artisan key:generate
      - run: php artisan test --env=testing || true

  deploy:
    needs: laravel-tests
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g @railway/cli
      - run: railway up
